version: '3.7'

services:
  docusaurus:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/src
      - /src/node_modules
    # see the README.md for instructions to set up a .env file
    env_file:
      - .env
