[[redirects]]
  from = "/docs/agent/zh/docs/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/zh/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/pt/docs/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/pt/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/kr/docs/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/kr/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/health/tutorials/*"
  to = "/guides/monitor/:splat"

[[redirects]]
  from = "/docs/agent/guides/*"
  to = "/guides/:splat"

[[redirects]]
  from = "/docs/agent/tutorials/*"
  to = "/guides/:splat"

[[redirects]]
  from = "/docs/agent/step-by-step/*"
  to = "/guides/step-by-step/:splat"

[[redirects]]
  from = "/docs/agent/collectors/ebpf_process.plugin/"
  to = "/docs/agent/collectors/ebpf.plugin/"

[[redirects]]
  from = "/docs/agent/netdata-cloud/*"
  to = "/docs/cloud/"

[[redirects]]
  from = "dbengine-calc"
  to = "/docs/agent/database/calculator"
