[[redirects]]
  from = "/docs/agent/zh/docs/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/zh/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/pt/docs/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/pt/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/kr/docs/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/kr/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/collectors/ebpf_process.plugin/"
  to = "/docs/agent/collectors/ebpf.plugin/"

[[redirects]]
  from = "/docs/agent/netdata-cloud/*"
  to = "/docs/cloud/"