name: Check for broken links

on: [pull_request, push]

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: waitFor200
        with:
          site_name: "netdata-docusaurus"
          max_timeout: 300

      - name: Check for broken links
        id: link-report
        uses: joelhans/link-checker@master
        with:
          url: 'https://deploy-preview-${{ github.event.pull_request.number }}--netdata-docusaurus.netlify.com'
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
