name: Test external links
on:
  schedule:
    - cron:  '30 20 * * 4'
env:
  WEBSITE_URL: "https://learn.netdata.cloud/"
  ISSUE_TEMPLATE: ".github/workflows/check-broken-links.md"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Run BLC on external links
      run: npx broken-link-checker $WEBSITE_URL --ordered --recursive --exclude-internal --exclude "https://netdata.cloud/" --exclude "https://www.linkedin.com/company/my-netdata.io/" --exclude "https://github.com/"

    - uses: actions/checkout@v2
      if: failure()

    - uses: JasonEtco/create-an-issue@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ env.ISSUE_TEMPLATE }}
      if: failure()
