name: Test internal links
on:
  schedule:
    - cron:  '30 0 * * *'
env:
  WEBSITE_URL: "https://learn.netdata.cloud/"
  ISSUE_TEMPLATE: ".github/workflows/check-broken-links.md"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Run BLC on internal links
      run: npx broken-link-checker $WEBSITE_URL --ordered --recursive --exclude-external

    - uses: actions/checkout@v2
      if: failure()

    - uses: JasonEtco/create-an-issue@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ env.ISSUE_TEMPLATE }}
      if: failure()
