name: Test external links
on:
  schedule:
    - cron:  '30 20 * * 5'
env:
  WEBSITE_URL: "https://learn.netdata.cloud/"
  ISSUE_TEMPLATE: ".github/workflows/check-broken-links.md"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Run BLC on external links
      run: npx broken-link-checker $WEBSITE_URL -rof --exclude-internal --requests=2 --exclude "netdata.cloud/" --exclude "daemon.io" --exclude "community.mellanox.com" --exclude "support.discordapp.com" --exclude "wiki.squid-cache.org" --exclude "pi-hole.net" --exclude "https://www.linkedin.com/company/my-netdata.io/" --exclude "https://github.com/" --exclude "my-netdata.io" --exclude "http://localhost" --exclude "firehol.org" --exclude "circleci.com" --exclude "redis.io" --exclude "telegram.org" --exclude "t.me"

    - uses: actions/checkout@v2
      if: failure()

    - uses: JasonEtco/create-an-issue@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: ${{ env.ISSUE_TEMPLATE }}
      if: failure()
